### PR TITLE
Option to isolate profiles for chromium-based browers

### PR DESCRIPTION
**Pull request by rhein**
Changes integrated:

1. Use a unique WMClass for each App ("ICE-SSB-" & sanitized app name)
2. New Option (UI: Checkbox) to request isolated instances

This is useful e.g. for running a G-Mail instance separate from normal browsing etc.
Also, using separate instances is apparently the only way to make SSB-Apps have their own Icon in KDE (see Issue #16 )

### CODE REVIEW

**Comment by Mark-Peppermint** [comment]
I **really** like this, but Firefox SSB's aren't getting a separate profile...

For example, iif I create 2 Fx SSB's:-

Name: Peppermint Forum One
URL: https://forum.peppermintos.com

and

Name: Peppermint Forum Two
URL: https://forum.peppermintos.com

They both share the same profile at
~/.local/share/ice/firefox/forum.peppermintos.com
so can't be run concurrently. They **do** have unique WMClass's which is great, but any idea how they could have separate profile directories, like you've done with the Chrome/Chormium profile separation ?

**Comment by rhein** [comment]
Interesting case, I did not consider this. For Firefox profiles are build based on the URL, while my fix uses the title. So yes, this certainly needs fixing. I think I can do this, just keeping it backward-compatible with the existing implementation might be a bit tricky. I'll come back on this.

**Comment by rhein** [comment]
Thinking about this a bit more I believe we can easily get rid the whole ice-firefox setup and have firefox work like any other browser (for newly created ICE-Apps anyway). Would that be ok or is there any dependency outside of ice to use ice-firefox?

**Comment by Mark-Peppermint** [comment]
How I see it is ice-firefox is necessary to set up the chromeless window for a Firefox SSB (as Firefox has no --app=url option.

Currently Firefox SSB's are ALREADY separated by having their own profiles .. this was necessary becuase of the way Firefox works

All that really needs to be added is a method for a Firefox SSB's to name their profile directory in line with the name etered as they're created rather than the URL .. currently they if you create 2 Firefox SSB's this happens...

Name: Peppermint Forum One
URL: https://forum.peppermintos.com

and

Name: Peppermint Forum Two
URL: https://forum.peppermintos.com

they both end up with their profile directory at
**~/.local/share/ice/firefox/forum.peppermintos.com**
because thee profile directory is being created from the URL instead of the name. It would be better if their profile directory was created from the SSB's given "Name:" field instead (as you're doing with the chromium based ones when the 'isolate' tickbox is ticked.

Just to be clear, for Firefox SSB's the 'isolate' tickbox can be ignored, as they're already isolated .. this is simply about naming the profile directories based on the name rather than URL (but also making sure they're properly cleaned up on removal).

Did that make any sense ?

**Comment by rhein** [comment]
Yes, that absolutely makes sense, I have already adapted it this way.
But all ice-firefox really does is to create the settings for the chromeless Firefox window every time the SSB is started. This can however also be done only once (when creating the SSB).
Code is updated to reflect this if you want to test, no more use of ice-firefox.
I am still looking at some minor issues though, so this is not yet final.

**Comment by Mark-Peppermint** [comment]
Nice, I'll take it for a spin .. cheers :)

**Comment by Mark-Peppermint** [comment]
Now that I'm seriously liking, thanks very much :)

What are the bugs you're looking at ?

One thing I've noticed (that has always been present with Firefox SSB's but is now also present with Chromium based ones is that if an SSB is left open, and you remove it in ICE, the profile directory gets recreated by the running browser .. so when you exit the SSB it's no longer listed in ICE's 'remove' tab, but there **is** still a profile directory.

As I said, this isn't anything new that's been introduced .. just something I thought I'd mention in case you have any ideas.

**Comment by rhein** [comment]
That's a tricky one, but I guess we could simply include some kind of cleanup check every time the "Remove" Tab is opened: if there are profiles but no matching .desktop files, remove those profile folders.
Its a bit in-transparent to the user, but I'd say it is ok for the ICE app to clean its own directory. Or we integrate a button "Clean orphaned profiles" in case such profiles are found. I'll have a look.
As for the bugs: I got the feeling that sometimes overwriting an existing .desktop file does not really work. But that might also be a KDE caching issue.

**Comment by Mark-Peppermint** [comment]
Either option would be cool, they both have their merits. Really appreciate the work you're putting into this.

**Comment by rhein** [comment]
I implemented the silent option for now, that runs a cleanup every time the ice app starts. Found quite a bit old profiles for myself ;-)
It would not trigger right now if an ice-app is overwritten with a different browser (e.g. Firefox-App overwritten by Chromium-App -> Firefox-Profile will stay in place), but that might actually be a feature. Only when the App is finally deleted both profile-types would be cleaned eventually.
You can safely check it out, there only is a debug output but no actual removal going on for now. One problem that still needs to be solved is how to not delete legacy Firefox profiles (as they have a different name than is expected now).
As for the work: I have about 20 iced apps I use daily, so it really is about time to contribute a bit ...

**Comment by rhein** [comment]
OK, fixed the Firefox legacy profiles problem as well. Also, the orphan-check now works both ways for firefox profiles, and re-creates them if they got deleted for existing apps.
Deletion is still only giving debug output, we have to change this if all other tests look good.

**Comment by Mark-Peppermint** [comment]
Many thanks rhein, I'll test this first thing in the morning if you don't mind .. need sleep, after a late night yesterday and an early start today coffee just isn't cutting it any more I'm afraid :)

Loving the sound of the fix working in both directions .. nicely done.

BTW, I'm personally (from a Peppermint perspective) not that bothered about backwards compatibility with existing Firefox SSB's .. This will highly **_likely_** not get pushed as an update to current Peppermint versions and just used afresh in Peppermint 10 (due soon), but I guess it'd be handy for other projects that use ICE not to break earlier SSB's if they choose to push it as an update.

BTW, that reminds me, I need to change the "Where in the menu?" category names from
Sound & Video  -->  Multimedia
System Tools  -->  System
in line with the Xfce menu items (Peppermint now uses) .. but that's not important here, I can do that later. This bit is more a note to myself.

**Comment by Mark-Peppermint** [comment]
I've taken it out of debugging mode and have been testing it for a while now .. haven't found any bugs yet.
This is going to be a major upgrade for ICE :)

**Comment by rhein** [comment]
Yes, I'd suggest go keep ice-firefox live for now to keep backwards compatibility so things don't break. The branch is now updated with activated profile cleanup - from my side the code is ready, could not make out any more bugs. Go ahead with the release as it suits you, glad I could help to make one of my favourite tools even better.

**Comment by Mark-Peppermint** [comment]
Many thanks rhein .. v6.0.0 released.

**Comment by Mark-Peppermint** [comment]
Just noticed a problem with this rhein .. the
~/.local/ice/profiles
directory isn't being automatically created if it doesn't already exists:-

Traceback (most recent call last):
  File "/usr/bin/ice", line 818, in <module>
    window = Ice()
  File "/usr/bin/ice", line 764, in __init__
    clean_orphaned_profiles(known_profiles)
  File "/usr/bin/ice", line 379, in clean_orphaned_profiles
    for fl in os.listdir("{0}/{1}/".format(_ICE_DIR, p_type)):
FileNotFoundError: [Errno 2] No such file or directory: '/home/mark/.local/share/ice/profiles/'

**Comment by Mark-Peppermint** [comment]
Okay fixed it :)

**Comment by rhein** [comment]
you are right, sorry about this

**Pull request merged**
