### PR TITLE
Create profiles / firefox directory if not existing

### PR DESCRIPTION
**Pull request by rhein**
Fixing the potential firefox profile dir issue as well

### CODE REVIEW

**Comment by Mark-Peppermint** [comment]
Thanks again rhein :)

**Comment by Mark-Peppermint** [comment]
Hold on, we now have 2 x _PROFILES_DIR at lines 37 (the one I added) and 39 (I think the one you added)
Are they both necessary ?

**Comment by Mark-Peppermint** [comment]
Ignore that, I know what happened .. we were working on different branches .. I can fix it

**Comment by Mark-Peppermint** [comment]
All fixed in the main branch now :)

**Comment by rhein** [comment]
Alright :-)

I thought I did fix the merge conflict on my end, maybe that didn't work. Anyhow, this looks good now.

**Comment by Mark-Peppermint** [comment]
Thanks for looking it over .. much appreciated :)

**Pull request merged**
